## **Numerical Computing with Numpy**

In [2]:
v = [10,20,30]
m = [v,v,v]
m

[[10, 20, 30], [10, 20, 30], [10, 20, 30]]

In [3]:
v[0] = "python"
m

[['python', 20, 30], ['python', 20, 30], ['python', 20, 30]]

In [4]:
from copy import deepcopy

In [5]:
v[0] = 10
m = deepcopy(v)

In [6]:
m

[10, 20, 30]

In [7]:
v[0] = "python"

In [8]:
m

[10, 20, 30]

In [9]:
import array
a = array.array("f",[0.4,0.5,0.6])
a

array('f', [0.4000000059604645, 0.5, 0.6000000238418579])

In [10]:
a.append(2.0)
a

array('f', [0.4000000059604645, 0.5, 0.6000000238418579, 2.0])

In [11]:
a.tolist()

[0.4000000059604645, 0.5, 0.6000000238418579, 2.0]

## numpy

In [7]:
import numpy as np

In [13]:
a = np.array([0,0.5,1.0])
a

array([0. , 0.5, 1. ])

In [14]:
type(a)

numpy.ndarray

In [15]:
a = np.array(["A","b"])
a

array(['A', 'b'], dtype='<U1')

In [16]:
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
a.sum()

np.int64(90)

In [18]:
a.std()

np.float64(5.163977794943222)

In [19]:
a.cumsum()

array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])

In [20]:
x = [2,3,4]
2 * x

[2, 3, 4, 2, 3, 4]

In [21]:
type(a)

numpy.ndarray

In [22]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
2 * a

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [24]:
2 ** a

array([     4,     16,     64,    256,   1024,   4096,  16384,  65536,
       262144])

## universal functions

In [25]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04, 1.62754791e+05, 1.20260428e+06, 8.88611052e+06,
       6.56599691e+07])

In [26]:
np.sqrt(2.5)

np.float64(1.5811388300841898)

In [27]:
import math
math.sqrt(2.5)

1.5811388300841898

In [28]:
math.sqrt(a)

TypeError: only length-1 arrays can be converted to Python scalars

In [29]:
np.sqrt(a)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739, 4.        , 4.24264069])

In [30]:
%timeit math.sqrt(2.5)

83.1 ns ± 7.58 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [31]:
%timeit np.sqrt(2.5)

2.02 μs ± 150 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## multiple dimensions

In [32]:
b = np.array([ a , a * 2])
b

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36]])

In [33]:
b[0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
b[0,2]

np.int64(6)

In [44]:
c = np.zeros((2,3), dtype="i", order="C")
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [54]:
c = np.ones((2,3,4), dtype="i", order="C")
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [56]:
c.size

24

In [57]:
c.shape

(2, 3, 4)

In [58]:
c.ndim

3

## Reshaping and resizing

In [59]:
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
g.shape

(15,)

In [61]:
g.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
h = g.reshape((5, 3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [65]:
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [68]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [70]:
np.resize(g, (3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [73]:
np.resize(g, (4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0]])

In [74]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [75]:
np.hstack((h, h*2))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [76]:
np.vstack((h,h*2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [77]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [78]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Boolean Arrays

In [79]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [80]:
h > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [81]:
h == 5

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [82]:
(h == 5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [84]:
(h > 4) & (h <= 12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [89]:
h[h > 8]

array([ 9, 10, 11, 12, 13, 14])

In [91]:
np.where(h > 7,1,0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [92]:
np.where(h % 2 == 0, "even", "odd")

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')

## Speed comparison

In [2]:
# pure python
import random
I = 5000

# Generating an array of 5,000 x 5,000
%time mat = [[random.gauss(0, 1) for j in range(I)] for i in range(I)]

CPU times: user 23.6 s, sys: 671 ms, total: 24.3 s
Wall time: 24.4 s


In [3]:
mat[0][:5]

[-0.9800374247139202,
 -1.398705347581735,
 -0.7765678514255542,
 -0.397163178372972,
 -0.7878483080691646]

In [4]:
%time sum([sum(l) for l in mat])

CPU times: user 882 ms, sys: 4.01 ms, total: 886 ms
Wall time: 885 ms


1071.0755193698026

In [5]:
import sys
sum([sys.getsizeof(l) for l in mat])

209400000

In [8]:
# Numpy
%time mat = np.random.standard_normal((I, I))

CPU times: user 2 s, sys: 28.9 ms, total: 2.03 s
Wall time: 2.03 s


In [9]:
%time mat.sum()

CPU times: user 48.2 ms, sys: 3.97 ms, total: 52.2 ms
Wall time: 48.1 ms


np.float64(-687.9218791554417)

In [10]:
mat.nbytes

200000000

In [11]:
sys.getsizeof(mat)

200000128

## Structures Numpy Arrays

In [15]:
dt = np.dtype([("Name","S10"),("Age", "i4"),("Height","f"),("Children/Pets","i4",2)])
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

## Vectorization of code

vectorization of code is a strategy to get more compact code that is possibly executed faster.

In [20]:
r = np.arange(12).reshape((4,3))
s = np.arange(12).reshape((4,3)) * 0.5

In [21]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [23]:
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [24]:
# broadcasting
# combining objects of different shapes within a single operation
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [25]:
2 * r

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [28]:
s = np.arange(0, 12, 4)
s

array([0, 4, 8])

In [29]:
r + s

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [30]:
r.shape

(4, 3)

In [31]:
s.shape

(3,)

In [32]:
s = np.arange(0, 12, 3)

In [33]:
s.shape

(4,)

In [34]:
r + s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [35]:
r.transpose() + s

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [40]:
sr = s.reshape(-1,1)
sr.shape

(4, 1)

In [41]:
r.shape

(4, 3)

In [45]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
sr

array([[0],
       [3],
       [6],
       [9]])

In [43]:
r + sr

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [46]:
def f(x):
    return 3 * x

In [47]:
f(10)

30

In [48]:
f(r)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

## Memory Layout

In [49]:
x = np.random.standard_normal((1000000, 5))
y = 2 * x

In [51]:
c = np.array((x, y), order="C")
f = np.array((x, y), order="F")

In [52]:
x = 0.0; y = 0.0

In [54]:
c[:2].round(2)

array([[[ 1.91, -0.9 , -0.44, -2.08,  0.45],
        [-0.61, -0.79, -1.33, -0.55, -0.7 ],
        [ 0.96, -0.84, -0.68, -1.41,  0.84],
        ...,
        [-0.1 ,  2.14, -0.06, -1.07,  0.11],
        [ 0.12,  0.47,  1.03, -0.14, -1.99],
        [-0.48,  0.92, -1.27,  0.21, -1.04]],

       [[ 3.83, -1.8 , -0.88, -4.17,  0.89],
        [-1.23, -1.58, -2.67, -1.1 , -1.41],
        [ 1.93, -1.68, -1.36, -2.83,  1.68],
        ...,
        [-0.2 ,  4.27, -0.13, -2.14,  0.21],
        [ 0.23,  0.94,  2.06, -0.28, -3.99],
        [-0.96,  1.84, -2.54,  0.43, -2.09]]], shape=(2, 1000000, 5))

In [55]:
%time c.sum()

CPU times: user 25 ms, sys: 1.05 ms, total: 26.1 ms
Wall time: 20.9 ms


np.float64(3688.9465587426703)

In [56]:
%time c.cumsum()

CPU times: user 122 ms, sys: 24.1 ms, total: 146 ms
Wall time: 142 ms


array([1.91453651e+00, 1.01523994e+00, 5.74610880e-01, ...,
       3.69060646e+03, 3.69103421e+03, 3.68894656e+03], shape=(10000000,))