## **Numerical Computing with Numpy**

In [2]:
v = [10,20,30]
m = [v,v,v]
m

[[10, 20, 30], [10, 20, 30], [10, 20, 30]]

In [4]:
v[0] = "python"
m

[['python', 20, 30], ['python', 20, 30], ['python', 20, 30]]

In [6]:
from copy import deepcopy

In [11]:
v[0] = 10
m = deepcopy(v)

In [12]:
m

[10, 20, 30]

In [13]:
v[0] = "python"

In [14]:
m

[10, 20, 30]

In [21]:
import array
a = array.array("f",[0.4,0.5,0.6])
a

array('f', [0.4000000059604645, 0.5, 0.6000000238418579])

In [24]:
a.append(2.0)
a

array('f', [0.4000000059604645, 0.5, 0.6000000238418579, 2.0, 2.0])

In [23]:
a.tolist()

[0.4000000059604645, 0.5, 0.6000000238418579, 2.0]

## numpy

In [25]:
import numpy as np

In [29]:
a = np.array([0,0.5,1.0])
a

array([0. , 0.5, 1. ])

In [30]:
type(a)

numpy.ndarray

In [33]:
a = np.array(["A","b"])
a

array(['A', 'b'], dtype='<U1')

In [34]:
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
a.sum()

np.int64(90)

In [36]:
a.std()

np.float64(5.163977794943222)

In [37]:
a.cumsum()

array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])

In [38]:
x = [2,3,4]
2 * x

[2, 3, 4, 2, 3, 4]

In [39]:
type(a)

numpy.ndarray

In [40]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
2 * a

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [45]:
2 ** a

array([     4,     16,     64,    256,   1024,   4096,  16384,  65536,
       262144])

## universal functions

In [46]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04, 1.62754791e+05, 1.20260428e+06, 8.88611052e+06,
       6.56599691e+07])

In [48]:
np.sqrt(2.5)

np.float64(1.5811388300841898)

In [49]:
import math
math.sqrt(2.5)

1.5811388300841898

In [50]:
math.sqrt(a)

TypeError: only length-1 arrays can be converted to Python scalars

In [52]:
np.sqrt(a)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739, 4.        , 4.24264069])

In [53]:
%timeit math.sqrt(2.5)

32.1 ns ± 1.41 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [54]:
%timeit np.sqrt(2.5)

685 ns ± 20.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## multiple dimensions