## **Numerical Computing with Numpy**

In [2]:
v = [10,20,30]
m = [v,v,v]
m

[[10, 20, 30], [10, 20, 30], [10, 20, 30]]

In [3]:
v[0] = "python"
m

[['python', 20, 30], ['python', 20, 30], ['python', 20, 30]]

In [4]:
from copy import deepcopy

In [5]:
v[0] = 10
m = deepcopy(v)

In [6]:
m

[10, 20, 30]

In [7]:
v[0] = "python"

In [8]:
m

[10, 20, 30]

In [9]:
import array
a = array.array("f",[0.4,0.5,0.6])
a

array('f', [0.4000000059604645, 0.5, 0.6000000238418579])

In [10]:
a.append(2.0)
a

array('f', [0.4000000059604645, 0.5, 0.6000000238418579, 2.0])

In [11]:
a.tolist()

[0.4000000059604645, 0.5, 0.6000000238418579, 2.0]

## numpy

In [12]:
import numpy as np

In [13]:
a = np.array([0,0.5,1.0])
a

array([0. , 0.5, 1. ])

In [14]:
type(a)

numpy.ndarray

In [15]:
a = np.array(["A","b"])
a

array(['A', 'b'], dtype='<U1')

In [16]:
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
a.sum()

np.int64(90)

In [18]:
a.std()

np.float64(5.163977794943222)

In [19]:
a.cumsum()

array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])

In [20]:
x = [2,3,4]
2 * x

[2, 3, 4, 2, 3, 4]

In [21]:
type(a)

numpy.ndarray

In [22]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
2 * a

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [24]:
2 ** a

array([     4,     16,     64,    256,   1024,   4096,  16384,  65536,
       262144])

## universal functions

In [25]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04, 1.62754791e+05, 1.20260428e+06, 8.88611052e+06,
       6.56599691e+07])

In [26]:
np.sqrt(2.5)

np.float64(1.5811388300841898)

In [27]:
import math
math.sqrt(2.5)

1.5811388300841898

In [28]:
math.sqrt(a)

TypeError: only length-1 arrays can be converted to Python scalars

In [29]:
np.sqrt(a)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739, 4.        , 4.24264069])

In [30]:
%timeit math.sqrt(2.5)

83.1 ns ± 7.58 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [31]:
%timeit np.sqrt(2.5)

2.02 μs ± 150 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## multiple dimensions

In [32]:
b = np.array([ a , a * 2])
b

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36]])

In [33]:
b[0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
b[0,2]

np.int64(6)

In [44]:
c = np.zeros((2,3), dtype="i", order="C")
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [54]:
c = np.ones((2,3,4), dtype="i", order="C")
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [56]:
c.size

24

In [57]:
c.shape

(2, 3, 4)

In [58]:
c.ndim

3

## Reshaping and resizing

In [59]:
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
g.shape

(15,)

In [61]:
g.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
h = g.reshape((5, 3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [65]:
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [68]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [70]:
np.resize(g, (3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [73]:
np.resize(g, (4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0]])

In [74]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [75]:
np.hstack((h, h*2))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [76]:
np.vstack((h,h*2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [77]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [78]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Boolean Arrays

In [79]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [80]:
h > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [81]:
h == 5

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [82]:
(h == 5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [84]:
(h > 4) & (h <= 12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [89]:
h[h > 8]

array([ 9, 10, 11, 12, 13, 14])

In [91]:
np.where(h > 7,1,0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [92]:
np.where(h % 2 == 0, "even", "odd")

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')